import { expect, test } from '@playwright/test';

test('creates a case with multiple parties and opens its persisted detail', async ({ page }) => {
  const permissions = ['cases.read', 'cases.create', 'cases.update', 'cases.change_status', 'catalogs.read', 'users.read'];
  const user = { id: 'user-1', email: 'admin@example.com', name: 'Admin', avatarUrl: null, status: 'ACTIVE', version: 1, lastLoginAt: null, createdAt: '', updatedAt: '', role: { id: 'role-1', code: 'HEAD', name: 'Jefe' }, permissions };
  const catalogs = { contactKinds: [], contactCategories: [], contactChannels: [], addressTypes: [], caseTypes: [{ value: 'LABOR', label: 'Laboral' }], caseStatuses: [{ value: 'ACTIVE', label: 'Activo' }], participantRoles: [{ value: 'CLAIMANT', label: 'Actor/a' }, { value: 'DEFENDANT', label: 'Demandado/a' }], partySides: [{ value: 'OUR_SIDE', label: 'Nuestra parte' }, { value: 'COUNTERPART', label: 'Contraparte' }] };
  const contacts = [{ id: 'contact-1', displayName: 'Ana Pérez', kind: 'PERSON', categories: [], channels: [], addresses: [], relations: { cases: 0, representations: 0 } }, { id: 'contact-2', displayName: 'Empresa Sur', kind: 'ORGANIZATION', categories: [], channels: [], addresses: [], relations: { cases: 0, representations: 0 } }];
  let created: Record<string, unknown> | null = null;
  await page.route('**/api/v1/**', async (route) => { const request = route.request(); const url = new URL(request.url()); if (url.pathname.endsWith('/auth/me')) return route.fulfill({ json: { data: { user } } }); if (url.pathname.endsWith('/auth/csrf')) return route.fulfill({ json: { data: { csrfToken: 'csrf-cases' } } }); if (url.pathname.endsWith('/catalogs')) return route.fulfill({ json: { data: catalogs } }); if (url.pathname.endsWith('/courts')) return route.fulfill({ json: { data: [] } }); if (url.pathname.endsWith('/management-offices')) return route.fulfill({ json: { data: [] } }); if (url.pathname.endsWith('/users')) return route.fulfill({ json: { data: [user] } }); if (url.pathname.endsWith('/contacts')) return route.fulfill({ json: { data: contacts, meta: { nextCursor: null } } }); if (url.pathname.endsWith('/cases') && request.method() === 'POST') { const body = request.postDataJSON() as Record<string, unknown>; created = { ...body, id: 'case-created', version: 1, closedOn: null, archivedOn: null, createdAt: '', updatedAt: '', court: null, managementOffice: null, participants: [{ id: 'p1', role: 'CLAIMANT', side: 'OUR_SIDE', isClient: true, activeUntil: null, contact: { id: 'contact-1', displayName: 'Ana Pérez' }, representations: [] }, { id: 'p2', role: 'DEFENDANT', side: 'COUNTERPART', isClient: false, activeUntil: null, contact: { id: 'contact-2', displayName: 'Empresa Sur' }, representations: [] }], team: [{ id: 't1', role: 'PRIMARY', unassignedAt: null, user: { id: user.id, name: user.name, email: user.email } }], statusHistory: [{ id: 'h1', fromStatus: null, toStatus: 'ACTIVE', changedAt: '', changedBy: { id: user.id, name: user.name } }], summary: { subCases: 0, actions: 0, tasks: 0, notes: 0, documents: 0 } }; return route.fulfill({ status: 201, json: { data: created } }); } if (url.pathname.endsWith('/cases/case-created/subcases')) return route.fulfill({ json: { data: [] } }); if (url.pathname.endsWith('/cases/case-created/timeline')) return route.fulfill({ json: { data: [], meta: { nextCursor: null } } }); if (url.pathname.endsWith('/cases/case-created')) return route.fulfill({ json: { data: created } }); return route.fulfill({ status: 404, json: {} }); });
  await page.goto('/juicios/nuevo'); await page.getByLabel('Carátula').fill('Pérez c/ Empresa Sur'); await page.getByLabel('Número').fill('321/2026'); await page.getByLabel('Juzgado').fill('Juzgado Laboral 3'); await page.getByLabel('Oficina').fill('Oficina 12'); await page.getByRole('combobox', { name: 'Parte 1', exact: true }).selectOption('contact-1'); await page.getByRole('combobox', { name: 'Parte 2', exact: true }).selectOption('contact-2'); await page.getByRole('button', { name: 'Crear juicio' }).click(); await expect(page.getByRole('heading', { name: 'Pérez c/ Empresa Sur' })).toBeVisible(); await expect(page.getByText('Juzgado Laboral 3')).toBeVisible(); await expect(page.getByText('Oficina 12')).toBeVisible(); await page.getByRole('tab', { name: 'Partes y equipo' }).click(); await expect(page.getByText('Ana Pérez')).toBeVisible(); await expect(page.getByText('Empresa Sur', { exact: true })).toBeVisible();
});
