import { expect, test } from '@playwright/test';

test('uploads, versions and downloads a private PDF from a case action', async ({ page }) => {
  const permissions = ['cases.read', 'catalogs.read', 'actions.read', 'documents.read', 'documents.create', 'documents.version'];
  const user = { id: 'user-1', email: 'admin@example.com', name: 'Admin', avatarUrl: null, status: 'ACTIVE', version: 1, lastLoginAt: null, createdAt: '', updatedAt: '', role: { id: 'role-1', code: 'HEAD', name: 'Jefe' }, permissions };
  const legalCase = { id: 'case-1', caseNumber: '123/2026', title: 'Pérez c/ Empresa', type: 'LABOR', status: 'ACTIVE', startDate: '2026-01-10T00:00:00.000Z', closedOn: null, archivedOn: null, version: 1, createdAt: '', updatedAt: '', court: null, managementOffice: null, participants: [], team: [], statusHistory: [], summary: { subCases: 0, actions: 1, tasks: 0, notes: 0, documents: 0 } };
  const action = { id: 'action-1', caseId: 'case-1', subCase: null, title: 'Demanda presentada', type: 'FILING', documentAt: '2026-05-01T13:00:00.000Z', presentationAt: null, description: null, version: 1, uploadedBy: { id: 'user-1', name: 'Admin' }, documentCount: 0 };
  let versionCount = 0;
  const documentRecord = () => ({ id: 'document-1', title: 'Demanda firmada', category: 'PLEADING', description: null, caseId: 'case-1', subCaseId: null, actionId: 'action-1', taskId: null, noteId: null, version: Math.max(versionCount, 1), createdAt: '', updatedAt: '', createdBy: { id: 'user-1', name: 'Admin' }, versions: Array.from({ length: versionCount }, (_, index) => { const number = versionCount - index; return { id: `version-${number}`, versionNumber: number, originalName: number === 1 ? 'demanda.pdf' : `demanda-v${number}.pdf`, mimeType: 'application/pdf', sizeBytes: 64, sha256: 'a'.repeat(64), scanStatus: 'SKIPPED', scannedAt: '', createdAt: '', createdBy: { id: 'user-1', name: 'Admin' } }; }), latestVersion: versionCount ? { id: `version-${versionCount}`, versionNumber: versionCount, originalName: versionCount === 1 ? 'demanda.pdf' : `demanda-v${versionCount}.pdf`, mimeType: 'application/pdf', sizeBytes: 64, sha256: 'a'.repeat(64), scanStatus: 'SKIPPED', scannedAt: '', createdAt: '', createdBy: { id: 'user-1', name: 'Admin' } } : null });
  await page.route('**/api/v1/**', async (route) => { const request = route.request(); const url = new URL(request.url()); if (url.pathname.endsWith('/auth/me')) return route.fulfill({ json: { data: { user } } }); if (url.pathname.endsWith('/auth/csrf')) return route.fulfill({ json: { data: { csrfToken: 'csrf-documents' } } }); if (url.pathname.endsWith('/catalogs')) return route.fulfill({ json: { data: { contactKinds: [], contactCategories: [], contactChannels: [], addressTypes: [], caseTypes: [{ value: 'LABOR', label: 'Laboral' }], caseStatuses: [{ value: 'ACTIVE', label: 'Activo' }], participantRoles: [], partySides: [], actionTypes: [] } } }); if (url.pathname.endsWith('/cases/case-1/subcases')) return route.fulfill({ json: { data: [] } }); if (url.pathname.endsWith('/cases/case-1/timeline')) return route.fulfill({ json: { data: [], meta: { nextCursor: null } } }); if (url.pathname.endsWith('/cases/case-1/actions')) return route.fulfill({ json: { data: [action], meta: { nextCursor: null } } }); if (url.pathname.endsWith('/cases/case-1')) return route.fulfill({ json: { data: legalCase } }); if (url.pathname.endsWith('/documents') && request.method() === 'GET') return route.fulfill({ json: { data: versionCount ? [documentRecord()] : [], meta: { nextCursor: null } } }); if (url.pathname.endsWith('/documents') && request.method() === 'POST') { versionCount = 1; return route.fulfill({ status: 201, json: { data: documentRecord() } }); } if (url.pathname.endsWith('/documents/document-1/versions') && request.method() === 'POST') { versionCount = 2; return route.fulfill({ status: 201, json: { data: documentRecord() } }); } if (url.pathname.includes('/documents/document-1/versions/') && url.pathname.endsWith('/download')) return route.fulfill({ status: 200, headers: { 'content-type': 'application/pdf', 'content-disposition': 'attachment; filename="demanda.pdf"' }, body: '%PDF-1.4\n%%EOF' }); return route.fulfill({ status: 404, json: {} }); });
  await page.goto('/juicios/case-1'); await page.getByRole('tab', { name: 'Documentos' }).click(); await expect(page.getByText('Todavía no hay documentos.')).toBeVisible(); await page.getByRole('button', { name: 'Subir PDF' }).click(); await page.getByLabel('Título').fill('Demanda firmada'); await page.getByLabel('Vincular a').selectOption('action-1'); await page.getByLabel('Archivo').setInputFiles({ name: 'demanda.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') }); await page.getByRole('button', { name: 'Subir', exact: true }).click(); await expect(page.getByText('v1 · demanda.pdf')).toBeVisible();
  await page.getByRole('button', { name: 'Nueva versión' }).click(); await page.getByLabel('Archivo PDF').setInputFiles({ name: 'demanda-v2.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nv2\n%%EOF') }); await page.getByRole('button', { name: 'Crear versión' }).click(); await expect(page.getByText('v2 · demanda-v2.pdf')).toBeVisible();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Descargar' }).first().click(); const download = await downloadPromise; expect(download.suggestedFilename()).toBe('demanda-v2.pdf');
});
