import { expect, test } from '@playwright/test';
const permissions = ['dashboard.read', 'feedback.create', 'feedback.manage'];
const user = { id: 'user-1', email: 'admin@example.com', name: 'Admin', avatarUrl: null, status: 'ACTIVE', version: 1, lastLoginAt: null, createdAt: '', updatedAt: '', role: { id: 'role-1', code: 'HEAD', name: 'Jefe' }, permissions };
test('reads notifications, saves preferences and resolves submitted feedback', async ({ page }) => { let read = false; let feedback: Record<string, unknown>[] = []; let preferenceSaved = false;
  await page.route('**/api/v1/**', async (route) => { const request = route.request(); const url = new URL(request.url());
    if (url.pathname.endsWith('/auth/me')) return route.fulfill({ json: { data: { user } } }); if (url.pathname.endsWith('/auth/csrf')) return route.fulfill({ json: { data: { csrfToken: 'csrf-notify' } } });
    if (url.pathname.endsWith('/dashboard')) return route.fulfill({ json: { data: { range: { from: null, to: null }, kpis: { activeCases: null, openTasks: null, overdueTasks: null, dueToday: null, activeClients: null }, myTasks: [], activity: [] } } });
    if (url.pathname.endsWith('/notifications') && request.method() === 'GET') return route.fulfill({ json: { data: [{ id: 'notification-1', type: 'TASK_ASSIGNED', title: 'Nueva tarea asignada', body: 'Preparar audiencia', entityType: 'Task', entityId: 'task-1', readAt: read ? '2026-09-19T13:00:00.000Z' : null, createdAt: '2026-09-19T12:00:00.000Z' }], meta: { nextCursor: null, unreadCount: read ? 0 : 1 } } });
    if (url.pathname.endsWith('/notifications/notification-1/read')) { read = true; return route.fulfill({ status: 204 }); }
    if (url.pathname.endsWith('/notification-preferences') && request.method() === 'GET') return route.fulfill({ json: { data: { taskAssigned: true, taskDueSoon: true, taskOverdue: true, caseStatusChanged: true, emailEnabled: false, dueSoonLeadDays: 1 } } });
    if (url.pathname.endsWith('/notification-preferences') && request.method() === 'PATCH') { preferenceSaved = true; return route.fulfill({ json: { data: request.postDataJSON() } }); }
    if (url.pathname.endsWith('/feedback') && request.method() === 'POST') { const body = request.postDataJSON(); const item = { id: 'feedback-1', message: body.message, status: 'OPEN', resolution: null, createdAt: '', resolvedAt: null, submittedBy: { id: 'user-1', name: 'Admin' }, resolvedBy: null }; feedback = [item]; return route.fulfill({ status: 201, json: { data: item } }); }
    if (url.pathname.endsWith('/feedback') && request.method() === 'GET') return route.fulfill({ json: { data: feedback, meta: { nextCursor: null } } });
    if (url.pathname.endsWith('/feedback/feedback-1') && request.method() === 'PATCH') { const body = request.postDataJSON(); feedback = [{ ...feedback[0], ...body, resolvedBy: { id: 'user-1', name: 'Admin' } }]; return route.fulfill({ json: { data: feedback[0] } }); }
    return route.fulfill({ status: 404, json: {} });
  });
  await page.goto('/'); await page.getByRole('button', { name: 'Notificaciones, 1 sin leer' }).click(); await expect(page.getByText('Preparar audiencia')).toBeVisible(); await page.getByText('Preparar audiencia').click(); await expect(page.getByRole('button', { name: 'Notificaciones' })).toBeVisible(); await page.getByRole('button', { name: 'Preferencias de notificaciones' }).click(); await page.getByLabel('Avisar con días de anticipación').fill('3'); await page.getByRole('button', { name: 'Guardar' }).click(); expect(preferenceSaved).toBe(true); await page.keyboard.press('Escape'); await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'Sugerencias' }).click(); await page.getByRole('button', { name: 'Sugerir mejora' }).click(); await page.getByLabel('Sugerencia', { exact: true }).fill('Agregar exportación de métricas'); await page.getByRole('button', { name: 'Enviar sugerencia' }).click(); await expect(page.getByText('Sugerencia enviada correctamente.')).toBeVisible();
  await expect(page.getByText('Agregar exportación de métricas')).toBeVisible(); page.once('dialog', (dialog) => dialog.accept('Incluido en roadmap')); await page.getByRole('button', { name: 'Resolver' }).click(); await expect(page.getByText('Resolución: Incluido en roadmap')).toBeVisible();
});
