import { useEffect, useMemo, useState, type DragEvent, type FormEvent } from 'react';
import { CalendarIcon, LayoutGrid, List, MessageSquare, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../auth/AuthContext';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { getCases } from '../features/cases/api';
import type { LegalCase } from '../features/cases/types';
import { getUsers } from '../features/team/api';
import type { TeamUser } from '../features/team/types';
import { addTaskComment, assignTask, createTask, getTasks, transitionTask } from '../features/tasks/api';
import type { Task, TaskPriority, TaskStatus } from '../features/tasks/types';
import { ApiProblem } from '../lib/api';

const columns: Array<{ status: TaskStatus; label: string }> = [
  { status: 'PENDING', label: 'Pendientes' }, { status: 'IN_PROGRESS', label: 'En progreso' },
  { status: 'COMPLETED', label: 'Completadas' }, { status: 'CANCELLED', label: 'Canceladas' },
];
const priorityLabel: Record<TaskPriority, string> = { LOW: 'Baja', MEDIUM: 'Media', HIGH: 'Alta', URGENT: 'Urgente' };
const errorMessage = (error: unknown) => error instanceof ApiProblem ? error.message : 'No se pudo completar la operación.';
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'short' }).format(new Date(value)) : 'Sin vencimiento';

export const Tasks = () => {
  const { can } = useAuth(); const [tasks, setTasks] = useState<Task[]>([]); const [users, setUsers] = useState<TeamUser[]>([]); const [cases, setCases] = useState<LegalCase[]>([]); const [loading, setLoading] = useState(true); const [view, setView] = useState<'kanban' | 'list'>('kanban'); const [createOpen, setCreateOpen] = useState(false); const [selectedId, setSelectedId] = useState<string | null>(null); const [draggedId, setDraggedId] = useState<string | null>(null); const [priority, setPriority] = useState<'ALL' | TaskPriority>('ALL'); const [assignee, setAssignee] = useState('ALL');
  const selected = useMemo(() => tasks.find((task) => task.id === selectedId) ?? null, [tasks, selectedId]);
  const shown = useMemo(() => tasks.filter((task) => (priority === 'ALL' || task.priority === priority) && (assignee === 'ALL' || task.assignees.some((user) => user.id === assignee))), [tasks, priority, assignee]);
  useEffect(() => { let active = true; setLoading(true); void Promise.all([getTasks(), getUsers(), getCases({ limit: 100 })]).then(([taskPage, nextUsers, casePage]) => { if (!active) return; setTasks(taskPage.data); setUsers(nextUsers.filter((user) => user.status === 'ACTIVE')); setCases(casePage.data); }).catch((error) => { if (active) toast.error(errorMessage(error)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const replace = (value: Task) => setTasks((current) => current.map((task) => task.id === value.id ? value : task));

  async function move(task: Task, status: TaskStatus) {
    if (task.status === status) return;
    const reasonRequired = status === 'CANCELLED' || task.status === 'COMPLETED' || task.status === 'CANCELLED' || (task.status === 'IN_PROGRESS' && status === 'PENDING');
    const reason = reasonRequired ? window.prompt('Indicá el motivo del cambio de estado:')?.trim() : undefined;
    if (reasonRequired && !reason) return;
    const snapshot = tasks; setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status, version: item.version + 1 } : item));
    try { replace(await transitionTask(task.id, { version: task.version, toStatus: status, ...(reason ? { reason } : {}) })); }
    catch (error) { setTasks(snapshot); toast.error(errorMessage(error)); }
  }
  function drop(event: DragEvent, status: TaskStatus) { event.preventDefault(); const task = tasks.find((item) => item.id === draggedId); setDraggedId(null); if (task) void move(task, status); }
  if (loading) return <p className="text-stone-500">Cargando tareas…</p>;

  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Tareas</h1><p className="text-stone-500">Actividades, responsables y vencimientos del estudio.</p></div><div className="flex gap-2"><div className="flex rounded-lg bg-stone-100 p-1"><Button variant={view === 'kanban' ? 'secondary' : 'ghost'} size="icon" aria-label="Vista tablero" onClick={() => setView('kanban')}><LayoutGrid className="h-4 w-4" /></Button><Button variant={view === 'list' ? 'secondary' : 'ghost'} size="icon" aria-label="Vista lista" onClick={() => setView('list')}><List className="h-4 w-4" /></Button></div>{can('tasks.create') ? <Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" /> Nueva tarea</Button> : null}</div></header>
    <div className="flex flex-wrap gap-3 rounded-xl border bg-white p-3"><select aria-label="Filtrar prioridad" className="h-9 rounded-md border px-3" value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}><option value="ALL">Todas las prioridades</option>{Object.entries(priorityLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar responsable" className="h-9 rounded-md border px-3" value={assignee} onChange={(event) => setAssignee(event.target.value)}><option value="ALL">Todos los responsables</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></div>
    {view === 'kanban' ? <div className="grid gap-4 xl:grid-cols-4">{columns.map((column) => { const items = shown.filter((task) => task.status === column.status); return <section key={column.status} aria-label={column.label} className="min-h-56 rounded-xl border bg-stone-50 p-3" onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, column.status)}><div className="mb-3 flex justify-between"><h2 className="font-semibold">{column.label}</h2><Badge variant="secondary">{items.length}</Badge></div><div className="space-y-3">{items.map((task) => <div key={task.id}><TaskCard task={task} onOpen={setSelectedId} onDrag={setDraggedId} /></div>)}{items.length === 0 ? <p className="rounded-lg border border-dashed p-6 text-center text-sm text-stone-400">Sin tareas</p> : null}</div></section>; })}</div> : <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-stone-50"><tr><th className="p-3">Tarea</th><th className="p-3">Estado</th><th className="p-3">Responsables</th><th className="p-3">Vencimiento</th></tr></thead><tbody>{shown.map((task) => <tr key={task.id} className="cursor-pointer border-t hover:bg-stone-50" onClick={() => setSelectedId(task.id)}><td className="p-3 font-medium">{task.title}</td><td className="p-3">{columns.find((column) => column.status === task.status)?.label}</td><td className="p-3">{task.assignees.map((user) => user.name).join(', ')}</td><td className="p-3">{formatDate(task.dueDate)}</td></tr>)}</tbody></table></div>}
    <CreateTaskDialog open={createOpen} users={users} cases={cases} onOpenChange={setCreateOpen} onCreated={(value) => setTasks((current) => [value, ...current])} />
    <TaskDetail task={selected} users={users} onOpenChange={(open) => { if (!open) setSelectedId(null); }} onMove={move} onReplace={replace} />
  </div>;
};

function TaskCard({ task, onOpen, onDrag }: { task: Task; onOpen(id: string): void; onDrag(id: string): void }) { return <article draggable onDragStart={() => onDrag(task.id)} onClick={() => onOpen(task.id)} className="cursor-grab rounded-lg border bg-white p-3 shadow-sm active:cursor-grabbing"><div className="flex justify-between gap-2"><Badge variant="outline" className={task.priority === 'URGENT' ? 'border-red-200 bg-red-50 text-red-700' : ''}>{priorityLabel[task.priority]}</Badge><span className="text-xs text-stone-500">{formatDate(task.dueDate)}</span></div><h3 className="mt-2 font-medium">{task.title}</h3>{task.case ? <p className="mt-1 truncate text-xs text-stone-500">{task.case.caseNumber} · {task.case.title}</p> : null}<div className="mt-3 flex -space-x-1">{task.assignees.map((user) => <span key={user.id} title={user.name} className="flex h-6 w-6 items-center justify-center rounded-full border bg-stone-100 text-[10px]">{user.name.charAt(0)}</span>)}</div></article>; }

function CreateTaskDialog({ open, users, cases, onOpenChange, onCreated }: { open: boolean; users: TeamUser[]; cases: LegalCase[]; onOpenChange(value: boolean): void; onCreated(value: Task): void }) {
  const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const assigneeIds = data.getAll('assigneeIds').map(String); if (!assigneeIds.length) return toast.error('Seleccioná al menos un responsable.'); setSubmitting(true); try { const dueDate = String(data.get('dueDate') ?? ''); const caseId = String(data.get('caseId') ?? ''); const value = await createTask({ title: String(data.get('title')), description: String(data.get('description') ?? ''), priority: String(data.get('priority')) as TaskPriority, assigneeIds, ...(dueDate ? { dueDate } : {}), ...(caseId ? { caseId } : {}) }); onCreated(value); onOpenChange(false); form.reset(); toast.success('Tarea creada.'); } catch (error) { toast.error(errorMessage(error)); } finally { setSubmitting(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={submit} className="space-y-4"><DialogHeader><DialogTitle>Nueva tarea</DialogTitle><DialogDescription>Podés seleccionar varios responsables.</DialogDescription></DialogHeader><Label htmlFor="task-title">Título</Label><Input id="task-title" name="title" required /><Label htmlFor="task-description">Descripción</Label><Textarea id="task-description" name="description" /><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="task-priority">Prioridad</Label><select id="task-priority" name="priority" className="mt-2 h-9 w-full rounded-md border px-3">{Object.entries(priorityLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><Label htmlFor="task-due">Vencimiento</Label><Input id="task-due" name="dueDate" type="date" className="mt-2" /></div></div><Label htmlFor="task-case">Expediente</Label><select id="task-case" name="caseId" className="h-9 w-full rounded-md border px-3"><option value="">Sin expediente</option>{cases.filter((item) => item.status !== 'ARCHIVED').map((item) => <option key={item.id} value={item.id}>{item.caseNumber} · {item.title}</option>)}</select><Label htmlFor="task-assignees">Responsables</Label><select id="task-assignees" name="assigneeIds" multiple required className="min-h-24 w-full rounded-md border p-2">{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><DialogFooter><Button type="submit" disabled={submitting}>Crear tarea</Button></DialogFooter></form></DialogContent></Dialog>;
}

function TaskDetail({ task, users, onOpenChange, onMove, onReplace }: { task: Task | null; users: TeamUser[]; onOpenChange(value: boolean): void; onMove(task: Task, status: TaskStatus): Promise<void>; onReplace(task: Task): void }) {
  const { can } = useAuth(); const [commenting, setCommenting] = useState(false);
  async function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!task) return; const ids = new FormData(event.currentTarget).getAll('userIds').map(String); if (!ids.length) return toast.error('Seleccioná al menos un responsable.'); try { onReplace(await assignTask(task.id, ids)); toast.success('Responsables actualizados.'); } catch (error) { toast.error(errorMessage(error)); } }
  async function comment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!task) return; const form = event.currentTarget; const content = String(new FormData(form).get('content') ?? '').trim(); if (!content) return; setCommenting(true); try { const value = await addTaskComment(task.id, content); onReplace({ ...task, comments: [...task.comments, value] }); form.reset(); } catch (error) { toast.error(errorMessage(error)); } finally { setCommenting(false); } }
  return <Dialog open={!!task} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">{task ? <div className="space-y-5"><DialogHeader><div className="flex gap-2"><Badge>{priorityLabel[task.priority]}</Badge><Badge variant="outline">{columns.find((column) => column.status === task.status)?.label}</Badge></div><DialogTitle>{task.title}</DialogTitle><DialogDescription>{task.description || 'Sin descripción.'}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="rounded border p-3"><p className="text-xs uppercase text-stone-400">Vencimiento</p><p className="flex items-center gap-2"><CalendarIcon className="h-4 w-4" /> {formatDate(task.dueDate)}</p></div><div className="rounded border p-3"><p className="text-xs uppercase text-stone-400">Expediente</p><p>{task.case ? `${task.case.caseNumber} · ${task.case.title}` : 'Sin expediente'}</p></div></div>{can('tasks.change_status') ? <div><Label htmlFor="detail-status">Cambiar estado</Label><select id="detail-status" aria-label="Cambiar estado" className="mt-2 h-9 w-full rounded-md border px-3" value={task.status} onChange={(event) => void onMove(task, event.target.value as TaskStatus)}>{columns.map((column) => <option key={column.status} value={column.status}>{column.label}</option>)}</select></div> : null}{can('tasks.assign') ? <form onSubmit={assign} className="space-y-2"><Label htmlFor="detail-assignees">Responsables</Label><select id="detail-assignees" name="userIds" multiple defaultValue={task.assignees.map((user) => user.id)} className="min-h-24 w-full rounded-md border p-2">{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><Button type="submit" variant="outline">Guardar responsables</Button></form> : null}<section className="space-y-3"><h3 className="flex items-center gap-2 font-semibold"><MessageSquare className="h-4 w-4" /> Comentarios</h3>{task.comments.map((item) => <div key={item.id} className="rounded border p-3"><p>{item.content}</p><p className="mt-1 text-xs text-stone-500">{item.author.name}</p></div>)}{can('tasks.update') ? <form onSubmit={comment} className="flex gap-2"><Input name="content" aria-label="Nuevo comentario" required placeholder="Agregar comentario…" /><Button type="submit" disabled={commenting}>Enviar</Button></form> : null}</section><section><h3 className="font-semibold">Historial</h3><div className="mt-2 space-y-2">{task.history.map((item) => <p key={item.id} className="text-sm text-stone-600">{columns.find((column) => column.status === item.toStatus)?.label} · {item.changedBy.name}{item.reason ? ` · ${item.reason}` : ''}</p>)}</div></section></div> : null}</DialogContent></Dialog>;
}
