export type CaseStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'CLOSED' | 'ARCHIVED';
export type CaseType = 'LABOR' | 'CIVIL_COMMERCIAL' | 'CRIMINAL' | 'FAMILY' | 'OTHER';
export interface CaseParticipant { id: string; role: string; side: string; isClient: boolean; label: string | null; notes: string | null; sortOrder: number; activeFrom: string | null; activeUntil: string | null; contact: { id: string; kind: string; displayName: string }; representations: Array<{ id: string; type: string; isPrimary: boolean; activeFrom: string | null; activeUntil: string | null; representative: { id: string; displayName: string } }> }
export interface CaseTeamMember { id: string; role: 'PRIMARY' | 'COLLABORATOR'; assignedAt: string; unassignedAt: string | null; user: { id: string; name: string; email: string } }
export interface StatusHistory { id: string; fromStatus: CaseStatus | null; toStatus: CaseStatus; reason: string | null; changedAt: string; changedBy: { id: string; name: string } }
export interface LegalCase { id: string; caseNumber: string; title: string; type: CaseType; status: CaseStatus; startDate: string; closedOn: string | null; archivedOn: string | null; version: number; createdAt: string; updatedAt: string; court: { id: string; name: string } | null; managementOffice: { id: string; name: string } | null; courtName: string | null; managementOfficeName: string | null; participants: CaseParticipant[]; team: CaseTeamMember[]; statusHistory: StatusHistory[]; summary: { subCases: number; actions: number; tasks: number; notes: number; documents: number } }
export interface Court { id: string; name: string; jurisdiction: string | null; address: string | null; isActive: boolean; offices: Array<{ id: string; name: string; address: string | null; isActive: boolean }> }
export interface Office { id: string; name: string; address: string | null; isActive: boolean; courts: Array<{ id: string; name: string; isActive: boolean }> }
export interface CreateCaseInput { caseNumber: string; title: string; type: CaseType; status: 'PENDING' | 'ACTIVE'; startDate: string; courtId?: string | null; managementOfficeId?: string | null; courtName?: string | null; managementOfficeName?: string | null; participants: Array<{ contactId: string; role: string; side: string; isClient: boolean; sortOrder?: number }>; representations?: []; team: Array<{ userId: string; role: 'PRIMARY' | 'COLLABORATOR' }> }
