import { useEffect, useState, type FormEvent } from 'react'; import { Bell, CheckCheck, Settings } from 'lucide-react'; import { toast } from 'sonner'; import { Button } from '../../components/ui/button'; import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog'; import { Input } from '../../components/ui/input'; import { getNotificationPreferences, getNotifications, readAllNotifications, readNotification, saveNotificationPreferences } from './api'; import type { Notification, NotificationPreference } from './types';
const defaults: NotificationPreference = { taskAssigned: true, taskDueSoon: true, taskOverdue: true, caseStatusChanged: true, emailEnabled: false, dueSoonLeadDays: 1 };
export function NotificationsButton() { const [open, setOpen] = useState(false); const [settings, setSettings] = useState(false); const [items, setItems] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [preferences, setPreferences] = useState(defaults);
  async function load() { try { const response = await getNotifications(); setItems(response.data); setUnread(response.meta.unreadCount); } catch { /* the header remains usable */ } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 60_000); return () => window.clearInterval(timer); }, []);
  async function mark(item: Notification) { if (!item.readAt) { await readNotification(item.id); setItems((current) => current.map((value) => value.id === item.id ? { ...value, readAt: new Date().toISOString() } : value)); setUnread((value) => Math.max(0, value - 1)); } }
  async function all() { await readAllNotifications(); setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() }))); setUnread(0); }
  async function openSettings() { try { setPreferences(await getNotificationPreferences()); setSettings(true); } catch { toast.error('No se pudieron cargar las preferencias.'); } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { setPreferences(await saveNotificationPreferences({ taskAssigned: data.has('taskAssigned'), taskDueSoon: data.has('taskDueSoon'), taskOverdue: data.has('taskOverdue'), caseStatusChanged: data.has('caseStatusChanged'), dueSoonLeadDays: Number(data.get('dueSoonLeadDays')) })); setSettings(false); toast.success('Preferencias guardadas.'); } catch { toast.error('No se pudieron guardar las preferencias.'); } }
  return <><Button type="button" variant="ghost" size="icon" aria-label={`Notificaciones${unread ? `, ${unread} sin leer` : ''}`} className="relative" onClick={() => setOpen(true)}><Bell className="h-5 w-5" />{unread ? <span className="absolute right-0 top-0 min-w-4 rounded-full bg-red-600 px-1 text-[10px] text-white">{unread}</span> : null}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><div className="flex items-center justify-between gap-3"><DialogTitle>Notificaciones</DialogTitle><div><Button variant="ghost" size="icon" aria-label="Preferencias de notificaciones" onClick={() => void openSettings()}><Settings className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Marcar todas como leídas" onClick={() => void all()}><CheckCheck className="h-4 w-4" /></Button></div></div></DialogHeader>{items.length ? <div className="space-y-2">{items.map((item) => <button type="button" key={item.id} onClick={() => void mark(item)} className={`w-full rounded-lg border p-3 text-left ${item.readAt ? 'bg-white' : 'border-stone-300 bg-stone-50'}`}><strong className="text-sm">{item.title}</strong>{item.body ? <p className="text-sm text-stone-600">{item.body}</p> : null}<time className="text-xs text-stone-400">{new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.createdAt))}</time></button>)}</div> : <p className="py-8 text-center text-stone-500">No hay notificaciones.</p>}</DialogContent></Dialog><Dialog open={settings} onOpenChange={setSettings}><DialogContent><form onSubmit={save} className="space-y-4"><DialogHeader><DialogTitle>Preferencias</DialogTitle></DialogHeader>{([['taskAssigned', 'Tareas asignadas'], ['taskDueSoon', 'Próximas a vencer'], ['taskOverdue', 'Tareas vencidas'], ['caseStatusChanged', 'Cambios de expediente']] as const).map(([name, label]) => <label key={name} className="flex gap-2"><input type="checkbox" name={name} defaultChecked={preferences[name]} /> {label}</label>)}<label htmlFor="lead-days">Avisar con días de anticipación</label><Input id="lead-days" name="dueSoonLeadDays" type="number" min="0" max="30" defaultValue={preferences.dueSoonLeadDays} /><DialogFooter><Button type="submit">Guardar</Button></DialogFooter></form></DialogContent></Dialog></>;
}
