const actionLabels: Record<string, string> = {
  AUTH_LOGIN_FAILED: 'registró un intento de acceso fallido',
  AUTH_LOGIN_SUCCEEDED: 'inició sesión',
  AUTH_LOGOUT: 'cerró sesión',
  AUTH_LOGOUT_ALL: 'cerró todas sus sesiones',
  AUTH_PASSWORD_RESET_REQUESTED: 'solicitó restablecer su contraseña',
  AUTH_PASSWORD_RESET_COMPLETED: 'restableció su contraseña',
  USER_CREATED: 'creó un usuario',
  USER_UPDATED: 'actualizó un usuario',
  USER_SESSIONS_REVOKED: 'revocó las sesiones de un usuario',
  USER_PASSWORD_RESET_ISSUED: 'emitió un restablecimiento de contraseña',
  ROLE_CREATED: 'creó un rol',
  ROLE_UPDATED: 'actualizó un rol',
  ROLE_PERMISSIONS_REPLACED: 'actualizó los permisos de un rol',
  CASE_CREATED: 'creó un expediente',
  CASE_UPDATED: 'actualizó un expediente',
  CASE_STATUS_CHANGED: 'cambió el estado de un expediente',
  CASE_DELETED: 'dio de baja un expediente',
  CASE_PARTICIPANT_ADDED: 'agregó una parte a un expediente',
  CASE_PARTICIPANT_UPDATED: 'actualizó una parte de un expediente',
  CASE_PARTICIPANT_REMOVED: 'quitó una parte de un expediente',
  CASE_REPRESENTATION_ADDED: 'agregó una representación',
  CASE_REPRESENTATION_REMOVED: 'quitó una representación',
  CASE_TEAM_ASSIGNED: 'asignó un integrante a un expediente',
  CASE_TEAM_UPDATED: 'actualizó el equipo de un expediente',
  TASK_CREATED: 'creó una tarea',
  TASK_UPDATED: 'actualizó una tarea',
  TASK_STATUS_CHANGED: 'cambió el estado de una tarea',
  TASK_ASSIGNED: 'actualizó los responsables de una tarea',
  TASK_COMMENT_CREATED: 'comentó una tarea',
  TASK_COMMENT_UPDATED: 'actualizó un comentario de tarea',
  TASK_COMMENT_DELETED: 'eliminó un comentario de tarea',
  CONTACT_CREATED: 'creó un contacto',
  CONTACT_UPDATED: 'actualizó un contacto',
  CONTACT_DELETED: 'dio de baja un contacto',
  CONTACT_CHANNEL_CREATED: 'agregó un canal de contacto',
  CONTACT_CHANNEL_UPDATED: 'actualizó un canal de contacto',
  CONTACT_CHANNEL_DELETED: 'eliminó un canal de contacto',
  CONTACT_ADDRESS_CREATED: 'agregó un domicilio',
  CONTACT_ADDRESS_UPDATED: 'actualizó un domicilio',
  CONTACT_ADDRESS_DELETED: 'eliminó un domicilio',
  ACTION_CREATED: 'registró una actuación',
  ACTION_UPDATED: 'actualizó una actuación',
  ACTION_DELETED: 'dio de baja una actuación',
  SUBCASE_CREATED: 'creó un cuaderno',
  SUBCASE_UPDATED: 'actualizó un cuaderno',
  SUBCASE_STATUS_CHANGED: 'cambió el estado de un cuaderno',
  SUBCASE_DELETED: 'dio de baja un cuaderno',
  DOCUMENT_CREATED: 'subió un documento',
  DOCUMENT_VERSION_CREATED: 'subió una nueva versión de un documento',
  DOCUMENT_UPDATED: 'actualizó un documento',
  DOCUMENT_ARCHIVED: 'archivó un documento',
  NOTE_CREATED: 'agregó una nota',
  FEEDBACK_CREATED: 'envió una sugerencia',
  FEEDBACK_UPDATED: 'actualizó una sugerencia',
  NOTIFICATION_PREFERENCES_UPDATED: 'actualizó sus preferencias de notificación',
  COURT_CREATED: 'creó un juzgado',
  COURT_UPDATED: 'actualizó un juzgado',
  MANAGEMENT_OFFICE_CREATED: 'creó una oficina de gestión',
  MANAGEMENT_OFFICE_UPDATED: 'actualizó una oficina de gestión',
};

const entityLabels: Record<string, string> = {
  LegalCase: 'Expedientes',
  Task: 'Tareas',
  Contact: 'Contactos',
  CaseAction: 'Actuaciones',
  SubCase: 'Cuadernos',
  Document: 'Documentos',
  Note: 'Notas',
  Feedback: 'Sugerencias',
  User: 'Usuarios',
  Session: 'Sesiones',
  PasswordResetToken: 'Recuperación de acceso',
  Role: 'Roles',
  Court: 'Juzgados',
  ManagementOffice: 'Oficinas de gestión',
  NotificationPreference: 'Preferencias de notificación',
};

export const auditEntityOptions = Object.entries(entityLabels).map(([value, label]) => ({ value, label }));

export const auditActionLabel = (action: string) => actionLabels[action] ?? action.toLowerCase().replaceAll('_', ' ');
export const auditEntityLabel = (entityType: string) => entityLabels[entityType] ?? entityType;
